### PR TITLE
Add fish completion

### PR DESCRIPTION
**Pull request by MindTooth**
Got around to create something.  Guess this is the most basic version for the completion.  Maybe you know of someone that can chime in?

Looked at some sort of excluding some completion if an options is set, e.g. `--edit-cask` don't need `--open-appcast`/`--open-home`, but came up empty.  Don't understand enough yet.

screen shot 2018-07-29 at 17 36 50
screen shot 2018-07-29 at 17 37 06

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> e.g. `--edit-cask` don't need `--open-appcast`/`--open-home`

That’s a perfectly valid thing to do. I may want to edit a `preflight` but also check if there’s a new version as long as I’m editing. No reason to exclude options.

**Comment by MindTooth** [comment]
Sure thing.  I'll test some more before I finish.

**Comment by MindTooth** [comment]
I do think it's okay enough to merge.  Atm. I don't know if it needs any advanced functions, and just be a reference for possible completions.

**Comment by vitorgalvao** [comment]
Merge away. Only thing I ask is that you PR the changes instead of directly merging, but other than that feel free to merge at your leisure, even if it’s a few seconds after submitting the PR.

**Comment by MindTooth** [comment]
Merged.  I'll be sure to do so.

**Pull request merged**
